
## 모든것은 항상 실패한다: 예외필터

--------------------

### 예외처리

* 소프트웨어에서 예외처리는 필수사항이다.
* 예외가 발생하는 모든곳에 예외처리 코드를 삽입하는것은 중복코드를 양산할뿐 기능구현과 관련 없는 코드로 핵심기능 구현에 집중하지 못한다.
* 예외가 발생했을때 에러로그와 콜스택을 남겨 디버깅에 사용할수 있는 별도의 모듈을 작성했다면, 에러처리기 역시 따로 만들어 한곳에서 공통으로 처리하도록 해야한다.
* Nest 역시 예외 레이어를 두고있다.
* 애플리케이션을 통틀어 제대로 처리하지 못한 예외를 처리하는 역활을 한다.
```
constructor(objectOrError?: string | object | any, descriptionOrOptions?: string | HttpExceptionOptions);
export declare class HttpException extends Error {
    .....
}
```
* Nest 는 예외에 대한 많은 클래스를 제공한다.
* 기본적으로 에러가 발생했을때 응답을 JSON 형식으로 바꿔주는데 이는 기본적으로 내장된 전역 예외 필터가 처리한다.
* 내장 예외필터는 인식할수 없는에러(HttpException 과 관련없는 에러)를 InternalServerErrorException 로 변환한다.
* InternalServerErrorException 는 HttpException 를 상속받고 있다.
* HttpException 는 Error 를 상속받는다
* JS 의 모든 에러는 Error 객체로부터 파생되었다.
```
@Get(':id')
findOne(@Param('id')id: string){
    if(+id < 1){
        throw new BadRequestException('0보다 큰 정수')
    }
    return this.usersService.findOne(id);
}
```
* 예외의 생성자에 전달할 메시지가 응답에 함께 출력되었다
```
export declare class HttpException extends Error {
    ....
    constructor(response: string | Record<string, any>, status: number, options?: HttpExceptionOptions);
}
```
* 생성자는 3개의 인수를 받는다
  * response: JSON 응답의 본문이다. 문자열이나 Record<string, any>, 타입의 객체를 전달할수 있다.
  * status: 에러의 속성을 나타내는 HTTP 상태코드
* JSON 응답의 본문은 statusCode 와 message 속성을 기본으로 가진다.
* 이값은 위에서 예외를 만들때 생성자에 넣어준 response 와 status 를 구성한다.
```
@Get(':id')
findOne(@Param('id')id: string){
    if(+id < 1){
        throw new HttpException(
            {
                errorMessage: 'id 는 0보다 큰 정수',
                foo: 'bar'
            },
            HttpStatus.BAD_REQUEST
        )
    }
    return this.usersService.findOne(id);
}
{
    errorMessage: 'id 는 0보다 큰 정수',
    foo: 'bar'
}
```
|         Nest 제공 표준 예외         |
|:-----------------------------:|
|      BadRequestException      |
| UnauthorizedException |
| NotFoundException |
| ForbiddenException |
| NotAcceptableException |
| RequestTimeoutException |
| ConflictException |
| GoneException |
| HttpVersionNotSupportedException |
| PayloadTooLargeException |
| UnsupportedMediaTypeException |
| UnprocessableEntityException |
| InternalServerErrorException |
| NotImplementedException |
| ImATeapotException |
| MethodNotAllowedException |
| BadGatewayException |
| ServiceUnavailableException |
| GatewayTimeoutException |
```
constructor(objectOrError?: string | object | any, descriptionOrOptions?: string | HttpExceptionOptions);
```
* Nest 제공 기본예외클래스는 모두 생성자가 위와 같은 모양을 가진다.
* BadRequestException 의 내부 구현을 보면 전달받은 objectOrError 와 desccription 으로 HttpException 생성자의 첫번째 인수를 구성한다.
```
export class BadRequestException extends HttpException {
  constructor(
    objectOrError?: string | object | any,
    descriptionOrOptions: string | HttpExceptionOptions = 'Bad Request',
  ) {
    const { description, httpExceptionOptions } =
      HttpException.extractDescriptionAndOptionsFrom(descriptionOrOptions);

    super(
      HttpException.createBody(
        objectOrError,
        description,
        HttpStatus.BAD_REQUEST,
      ),
      HttpStatus.BAD_REQUEST,
      httpExceptionOptions,
    );
  }
}
```

### 예외 필터

* Nest 에서 제공하는 전역 예외 필터 외에 직접 예외 필터 레이어를 둬 원하는대로 예외를 다룰수 있다.
* 예외가 일어났을때 로그를 남기거나 응답 객체를 원하는대로 변경하고자 하는등의 요구사항을 해결하고자 할때 사용한다.
* 예외가 발생했을때 모든 예외를 잡아서 요청 URL 과 예외가 발생한 시각을 콘솔에 출력하는 예외 필터를 만든다.
```
import {ArgumentsHost, Catch, ExceptionFilter, HttpException, InternalServerErrorException} from "@nestjs/common";
import {Request, Response} from "express";

@Catch() // 1
export class HttpExceptionFilter implements ExceptionFilter{
    catch(exception: Error, host: ArgumentsHost) {
        const ctx = host.switchToHttp();
        const res = ctx.getResponse<Response>();
        const req = ctx.getRequest<Request>();

        if(!(exception instanceof HttpException)){ // 2
            exception = new InternalServerErrorException();
        }
        const response = (exception as HttpException).getResponse();
        const log = {
            timestamp: new Date(),
            url: req.url,
            response,
        }
        console.log(log)
        res.status((exception as HttpException).getStatus()).json(response)
    }
}
```
1. @Catch 데커레이터는 처리되지 않은 모든 예외를 잡으려고 할때 사용한다.
2. 대부분의 에러는 이미 Nest 에서 HttpException 을 상속받는 클래스들로 제공한다. HttpException 이 아닌 예외는 알수 없는 에러이므로 InternalServerErrorException 으로 처리한다.
* HttpException 필터 적용하기
* 예외 필터는 @UserFilter 데커레이터로 컨트롤러에 직접 적용하거나 전역으로 사용할수 있다.
* 예외 필터는 전역필터를 하나만 가지도록 하는게 일반적이다.
```
// 특정 엔드포인트 적용
@UseFilters(HttpExceptionFilter)
@Post()
create(@Body() createUserDto: CreateUserDto) {
    return this.usersService.create(createUserDto);
}
// 특정 컨트롤러 전체 적용
@Controller('users')
@UseFilters(HttpExceptionFilter)
export class UsersController {
    ....
}
// 애플리케이션 전체 적용
async function bootstrap() {
    const app = await NestFactory.create(AppModule);
    app.useGlobalFilters(new HttpExceptionFilter());
    await app.listen(3000);
}
```
* 부트스트랩 과정에서 전역 필터를 적용하는 방식은 필터에 의존성을 주입할수 없다는 제약이 있다.
* 예외 필터의 수행이 예외가 발생한 모듈 외부에서 이뤄지기 때문이다.
* 의존성 주입을 받고자 하면 예외필터를 커스텀 프로바이더로 등록하면 된다.
```
@Module({
  providers: [
    AppService,
    Logger,
    {
      provide: APP_FILTER, 
      useClass: HttpExceptionFilter 
    },
  ],
  .....
})
```
* HttpExceptionFilter 는 다른 프로바이더를 주입받아 사용할수 있다.
* 외부 모듈에서 제공하는 Logger 객체를 사용한다면 아래처럼 구현한다.
```
@Catch()
export class HttpExceptionFilter implements ExceptionFilter {
    constructor(private logger: Logger) { }
    ....
}
```
```
{
  timestamp: 2023-08-30T05:49:30.312Z,
  url: '/users/0',
  response: { statusCode: 400, message: 'Bad Request' }
}
```
* 예외 필터는 try/catch 로 잡지 못한 예외가 발생했을때 실행된다.
* 잡지못한 예외가 발생하면 나머지 생명주기를 무시하고 예외 필터로 건너 뛴다.

### 유저 서비스에 예외 필터 적용하기

```
@Module({
    // 1
    providers: [
      Logger,
      { provide: APP_FILTER, useClass: HttpExceptionFilter },
    ],
})
export class ExceptionModule {}
```
1. HttpExceptionFilter 와 주입받을 Logger 프로바이더를 선언한다.
```
@Module({
  imports: [
      ExceptionModule,
      .....
  ],
  .....
})
export class AppModule {}
```
* ExceptionModule 을 AppModule 로 가져온다.
```
@Catch()
export class HttpExceptionFilter implements ExceptionFilter{
    constructor(private logger: Logger) {}
    .......
        const stack = exception.stack;
        .......
        const log = {
            timestamp: new Date(),
            url: req.url,
            response,
            stack,
        }
        this.logger.log(log)
        ......
    }
}

[MyApp] Info  GMT+0900 (대한민국 표준시) undefined - {
  url: '/users/0',
  response: { statusCode: 400, message: 'Bad Request' },
  stack: 'BadRequestException: Bad Request\n' +
    '    at UsersController.findOne (C:\\Users\\kya10\\Desktop\\webstormWorkspace\\TIL\\NestJS\\src\\users\\users.controller.ts:34:19)\n' +
    '    at C:\\Users\\kya10\\Desktop\\webstormWorkspace\\TIL\\NestJS\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:38:29\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at C:\\Users\\kya10\\Desktop\\webstormWorkspace\\TIL\\NestJS\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n' +
    '    at C:\\Users\\kya10\\Desktop\\webstormWorkspace\\TIL\\NestJS\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17'
}
```